services:
  app-1:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ALL_NODE_IPS=app-1,app-2,app-3,app-4,app-5,app-6,app-7
      - CURRENT_NODE_IP=app-1

    ports:
      - "8001:8000"
  app-2:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ALL_NODE_IPS=app-1,app-2,app-3,app-4,app-5,app-6,app-7
      - CURRENT_NODE_IP=app-2

    ports:
      - "8002:8000"

  app-3:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ALL_NODE_IPS=app-1,app-2,app-3,app-4,app-5,app-6,app-7
      - CURRENT_NODE_IP=app-3

    ports:
      - "8003:8000"
  app-4:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ALL_NODE_IPS=app-1,app-2,app-3,app-4,app-5,app-6,app-7
      - CURRENT_NODE_IP=app-4

    ports:
      - "8004:8000"
  app-5:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ALL_NODE_IPS=app-1,app-2,app-3,app-4,app-5,app-6,app-7
      - CURRENT_NODE_IP=app-5

    ports:
      - "8005:8000"

  app-6:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ALL_NODE_IPS=app-1,app-2,app-3,app-4,app-5,app-6,app-7
      - CURRENT_NODE_IP=app-6

    ports:
      - "8006:8000"

  app-7:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ALL_NODE_IPS=app-1,app-2,app-3,app-4,app-5,app-6,app-7
      - CURRENT_NODE_IP=app-7

    ports:
      - "8007:8000"